version: '3.8'
services:
  mariadb:
    container_name: mariadb_container
    image: mariadb
    ports:
      - "13306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mydata:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - mjc_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  boot-app:
    image: asjcell/backend_image:v1.2.7
    container_name: boot_container
    ports:
      - "18888:8888"
    env_file:
      - .env  # .env 파일 로드
    environment:
      SPRING_PROFILES_ACTIVE: local
      TZ: Asia/Seoul
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - mjc_network

networks:
  mjc_network:
    driver: bridge